/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Time = IDL.Int;
export const Client = IDL.Record({
  'contactInfo' : IDL.Text,
  'name' : IDL.Text,
  'notes' : IDL.Opt(IDL.Text),
});
export const IntakeStatusHistoryEntry = IDL.Record({
  'status' : IDL.Text,
  'updatedBy' : IDL.Opt(IDL.Principal),
  'timestamp' : Time,
});
export const Intake = IDL.Record({
  'id' : IDL.Nat,
  'exitDate' : IDL.Opt(Time),
  'status' : IDL.Text,
  'client' : Client,
  'createdAt' : Time,
  'submittedBy' : IDL.Principal,
  'statusHistory' : IDL.Vec(IntakeStatusHistoryEntry),
  'reviewedBy' : IDL.Opt(IDL.Principal),
  'updatedAt' : Time,
  'details' : IDL.Text,
  'exitNotes' : IDL.Opt(IDL.Text),
  'internalNotes' : IDL.Opt(IDL.Text),
  'assignedBedId' : IDL.Opt(IDL.Nat),
  'caseManager' : IDL.Opt(IDL.Principal),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Program = IDL.Variant({
  'medicalStepDown' : IDL.Null,
  'workforceHousing' : IDL.Null,
});
export const Status__1 = IDL.Variant({
  'occupied' : IDL.Null,
  'available' : IDL.Null,
  'maintenance' : IDL.Null,
});
export const Bed = IDL.Record({
  'id' : IDL.Nat,
  'status' : Status__1,
  'occupant' : IDL.Opt(Client),
  'lastUpdated' : Time,
  'bedNumber' : IDL.Text,
  'isArchived' : IDL.Bool,
  'facilityId' : IDL.Nat,
  'program' : Program,
});
export const EntityType = IDL.Variant({
  'bed' : IDL.Null,
  'referral' : IDL.Null,
  'intake' : IDL.Null,
});
export const ActionType = IDL.Variant({
  'referralUpdated' : IDL.Null,
  'bedArchived' : IDL.Null,
  'referralStatusChanged' : IDL.Null,
  'bedAssigned' : IDL.Null,
  'bedUnassigned' : IDL.Null,
  'intakeCreated' : IDL.Null,
  'referralResubmitted' : IDL.Null,
  'referralCreated' : IDL.Null,
  'intakeStatusChanged' : IDL.Null,
});
export const ActivityLogEntry = IDL.Record({
  'entity' : EntityType,
  'action' : ActionType,
  'user' : IDL.Principal,
  'timestamp' : Time,
  'recordId' : IDL.Nat,
});
export const AdminStatusInfo = IDL.Record({
  'callerPrincipal' : IDL.Principal,
  'isAdmin' : IDL.Bool,
  'allAdminPrincipals' : IDL.Vec(IDL.Principal),
});
export const Facility = IDL.Record({
  'id' : IDL.Nat,
  'contactInfo' : IDL.Text,
  'name' : IDL.Text,
  'facilityType' : IDL.Text,
  'address' : IDL.Text,
});
export const Status = IDL.Variant({
  'submitted' : IDL.Null,
  'waitlisted' : IDL.Null,
  'approved' : IDL.Null,
  'declined' : IDL.Null,
  'needsInfo' : IDL.Null,
});
export const Document = IDL.Vec(IDL.Nat8);
export const StatusHistoryEntry = IDL.Record({
  'status' : Status,
  'updatedBy' : IDL.Opt(IDL.Principal),
  'timestamp' : Time,
});
export const Referral = IDL.Record({
  'id' : IDL.Nat,
  'status' : Status,
  'client' : Client,
  'documents' : IDL.Vec(Document),
  'referrerName' : IDL.Text,
  'clientName' : IDL.Text,
  'source' : IDL.Text,
  'partnerAgencyName' : IDL.Text,
  'createdAt' : Time,
  'submittedBy' : IDL.Opt(IDL.Principal),
  'statusHistory' : IDL.Vec(StatusHistoryEntry),
  'updatedAt' : Time,
  'assignedStaff' : IDL.Opt(IDL.Principal),
  'programRequested' : IDL.Text,
  'internalNotes' : IDL.Opt(IDL.Text),
  'requestMoreInfo' : IDL.Opt(IDL.Text),
  'reason' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'role' : IDL.Opt(IDL.Text),
  'email' : IDL.Opt(IDL.Text),
  'phone' : IDL.Opt(IDL.Text),
});
export const PartnerAgencyProfile = IDL.Record({
  'primaryContactName' : IDL.Text,
  'email' : IDL.Text,
  'agencyName' : IDL.Text,
  'phone' : IDL.Text,
});
export const AccessRequest = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  }),
  'contactName' : IDL.Text,
  'createdAt' : Time,
  'rejectionReason' : IDL.Opt(IDL.Text),
  'email' : IDL.Text,
  'agencyName' : IDL.Text,
  'notes' : IDL.Opt(IDL.Text),
  'phone' : IDL.Text,
  'assignedUser' : IDL.Opt(IDL.Principal),
});
export const ApprovalStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const UserApprovalInfo = IDL.Record({
  'status' : ApprovalStatus,
  'principal' : IDL.Principal,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addIntakeInternalNotes' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'addReferralInternalNotes' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'approveReferralAndCreateIntake' : IDL.Func(
      [IDL.Nat, IDL.Text],
      [Intake],
      [],
    ),
  'approveRequest' : IDL.Func([IDL.Nat, IDL.Principal], [], []),
  'archiveBed' : IDL.Func([IDL.Nat], [], []),
  'assignBed' : IDL.Func([IDL.Nat, Client], [], []),
  'assignBedToIntake' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignCaseManager' : IDL.Func([IDL.Nat, IDL.Opt(IDL.Principal)], [], []),
  'assignUserRequest' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
  'assignUserRole' : IDL.Func([IDL.Principal, IDL.Text], [], []),
  'createAccessRequest' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
      [IDL.Nat],
      [],
    ),
  'createBed' : IDL.Func([IDL.Nat, Program, IDL.Text], [IDL.Nat], []),
  'createFacility' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'createIntake' : IDL.Func([Client, IDL.Text], [IDL.Nat], []),
  'createReferral' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, Client, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'deleteBed' : IDL.Func([IDL.Nat], [], []),
  'deleteRequest' : IDL.Func([IDL.Nat], [], []),
  'ensureAdminRole' : IDL.Func([], [], []),
  'getActiveBeds' : IDL.Func([], [IDL.Vec(Bed)], ['query']),
  'getActivityLogEntries' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(ActivityLogEntry)],
      ['query'],
    ),
  'getAdminStatusCheck' : IDL.Func([], [AdminStatusInfo], ['query']),
  'getAllBeds' : IDL.Func([], [IDL.Vec(Bed)], ['query']),
  'getAllFacilities' : IDL.Func([], [IDL.Vec(Facility)], ['query']),
  'getAllIntakes' : IDL.Func([], [IDL.Vec(Intake)], ['query']),
  'getAllReferrals' : IDL.Func([], [IDL.Vec(Referral)], ['query']),
  'getAllReferralsForPartnerAgency' : IDL.Func(
      [],
      [IDL.Vec(Referral)],
      ['query'],
    ),
  'getAllUsers' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
      ['query'],
    ),
  'getAvailableBedsByProgram' : IDL.Func([Program], [IDL.Vec(Bed)], ['query']),
  'getBedsByProgram' : IDL.Func([Program], [IDL.Vec(Bed)], ['query']),
  'getCallerPartnerAgencyProfile' : IDL.Func(
      [],
      [IDL.Opt(PartnerAgencyProfile)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getIntake' : IDL.Func([IDL.Nat], [Intake], ['query']),
  'getIntakeStatusHistory' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(IntakeStatusHistoryEntry)],
      ['query'],
    ),
  'getMyReferrals' : IDL.Func([], [IDL.Vec(Referral)], ['query']),
  'getPendingRequests' : IDL.Func([], [IDL.Vec(AccessRequest)], ['query']),
  'getReferral' : IDL.Func([IDL.Nat], [Referral], ['query']),
  'getReferralForPartnerAgency' : IDL.Func([IDL.Nat], [Referral], ['query']),
  'getReferralStatusHistory' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(StatusHistoryEntry)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
  'isRequestApproved' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
  'listAdmins' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
  'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
  'markIntakeExited' : IDL.Func([IDL.Nat, Time, IDL.Text], [], []),
  'rejectRequest' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'removeUserRole' : IDL.Func([IDL.Principal], [], []),
  'requestApproval' : IDL.Func([], [], []),
  'requestMoreInfo' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'resubmitReferral' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, Client, IDL.Text],
      [],
      [],
    ),
  'reviewIntake' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'saveCallerPartnerAgencyProfile' : IDL.Func([PartnerAgencyProfile], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
  'updateBed' : IDL.Func(
      [IDL.Nat, Program, IDL.Text, Status__1, IDL.Opt(Client), IDL.Bool],
      [],
      [],
    ),
  'updateBedStatus' : IDL.Func([IDL.Nat, Status__1], [], []),
  'updateReferral' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, Client, IDL.Text],
      [],
      [],
    ),
  'updateReferralStatus' : IDL.Func(
      [IDL.Nat, Status, IDL.Opt(IDL.Principal)],
      [],
      [],
    ),
  'updateReferralStatusWithMessage' : IDL.Func(
      [IDL.Nat, Status, IDL.Opt(IDL.Text)],
      [],
      [],
    ),
  'uploadReferralDocuments' : IDL.Func([IDL.Nat, IDL.Vec(Document)], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Time = IDL.Int;
  const Client = IDL.Record({
    'contactInfo' : IDL.Text,
    'name' : IDL.Text,
    'notes' : IDL.Opt(IDL.Text),
  });
  const IntakeStatusHistoryEntry = IDL.Record({
    'status' : IDL.Text,
    'updatedBy' : IDL.Opt(IDL.Principal),
    'timestamp' : Time,
  });
  const Intake = IDL.Record({
    'id' : IDL.Nat,
    'exitDate' : IDL.Opt(Time),
    'status' : IDL.Text,
    'client' : Client,
    'createdAt' : Time,
    'submittedBy' : IDL.Principal,
    'statusHistory' : IDL.Vec(IntakeStatusHistoryEntry),
    'reviewedBy' : IDL.Opt(IDL.Principal),
    'updatedAt' : Time,
    'details' : IDL.Text,
    'exitNotes' : IDL.Opt(IDL.Text),
    'internalNotes' : IDL.Opt(IDL.Text),
    'assignedBedId' : IDL.Opt(IDL.Nat),
    'caseManager' : IDL.Opt(IDL.Principal),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Program = IDL.Variant({
    'medicalStepDown' : IDL.Null,
    'workforceHousing' : IDL.Null,
  });
  const Status__1 = IDL.Variant({
    'occupied' : IDL.Null,
    'available' : IDL.Null,
    'maintenance' : IDL.Null,
  });
  const Bed = IDL.Record({
    'id' : IDL.Nat,
    'status' : Status__1,
    'occupant' : IDL.Opt(Client),
    'lastUpdated' : Time,
    'bedNumber' : IDL.Text,
    'isArchived' : IDL.Bool,
    'facilityId' : IDL.Nat,
    'program' : Program,
  });
  const EntityType = IDL.Variant({
    'bed' : IDL.Null,
    'referral' : IDL.Null,
    'intake' : IDL.Null,
  });
  const ActionType = IDL.Variant({
    'referralUpdated' : IDL.Null,
    'bedArchived' : IDL.Null,
    'referralStatusChanged' : IDL.Null,
    'bedAssigned' : IDL.Null,
    'bedUnassigned' : IDL.Null,
    'intakeCreated' : IDL.Null,
    'referralResubmitted' : IDL.Null,
    'referralCreated' : IDL.Null,
    'intakeStatusChanged' : IDL.Null,
  });
  const ActivityLogEntry = IDL.Record({
    'entity' : EntityType,
    'action' : ActionType,
    'user' : IDL.Principal,
    'timestamp' : Time,
    'recordId' : IDL.Nat,
  });
  const AdminStatusInfo = IDL.Record({
    'callerPrincipal' : IDL.Principal,
    'isAdmin' : IDL.Bool,
    'allAdminPrincipals' : IDL.Vec(IDL.Principal),
  });
  const Facility = IDL.Record({
    'id' : IDL.Nat,
    'contactInfo' : IDL.Text,
    'name' : IDL.Text,
    'facilityType' : IDL.Text,
    'address' : IDL.Text,
  });
  const Status = IDL.Variant({
    'submitted' : IDL.Null,
    'waitlisted' : IDL.Null,
    'approved' : IDL.Null,
    'declined' : IDL.Null,
    'needsInfo' : IDL.Null,
  });
  const Document = IDL.Vec(IDL.Nat8);
  const StatusHistoryEntry = IDL.Record({
    'status' : Status,
    'updatedBy' : IDL.Opt(IDL.Principal),
    'timestamp' : Time,
  });
  const Referral = IDL.Record({
    'id' : IDL.Nat,
    'status' : Status,
    'client' : Client,
    'documents' : IDL.Vec(Document),
    'referrerName' : IDL.Text,
    'clientName' : IDL.Text,
    'source' : IDL.Text,
    'partnerAgencyName' : IDL.Text,
    'createdAt' : Time,
    'submittedBy' : IDL.Opt(IDL.Principal),
    'statusHistory' : IDL.Vec(StatusHistoryEntry),
    'updatedAt' : Time,
    'assignedStaff' : IDL.Opt(IDL.Principal),
    'programRequested' : IDL.Text,
    'internalNotes' : IDL.Opt(IDL.Text),
    'requestMoreInfo' : IDL.Opt(IDL.Text),
    'reason' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'role' : IDL.Opt(IDL.Text),
    'email' : IDL.Opt(IDL.Text),
    'phone' : IDL.Opt(IDL.Text),
  });
  const PartnerAgencyProfile = IDL.Record({
    'primaryContactName' : IDL.Text,
    'email' : IDL.Text,
    'agencyName' : IDL.Text,
    'phone' : IDL.Text,
  });
  const AccessRequest = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Variant({
      'pending' : IDL.Null,
      'approved' : IDL.Null,
      'rejected' : IDL.Null,
    }),
    'contactName' : IDL.Text,
    'createdAt' : Time,
    'rejectionReason' : IDL.Opt(IDL.Text),
    'email' : IDL.Text,
    'agencyName' : IDL.Text,
    'notes' : IDL.Opt(IDL.Text),
    'phone' : IDL.Text,
    'assignedUser' : IDL.Opt(IDL.Principal),
  });
  const ApprovalStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const UserApprovalInfo = IDL.Record({
    'status' : ApprovalStatus,
    'principal' : IDL.Principal,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addIntakeInternalNotes' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'addReferralInternalNotes' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'approveReferralAndCreateIntake' : IDL.Func(
        [IDL.Nat, IDL.Text],
        [Intake],
        [],
      ),
    'approveRequest' : IDL.Func([IDL.Nat, IDL.Principal], [], []),
    'archiveBed' : IDL.Func([IDL.Nat], [], []),
    'assignBed' : IDL.Func([IDL.Nat, Client], [], []),
    'assignBedToIntake' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignCaseManager' : IDL.Func([IDL.Nat, IDL.Opt(IDL.Principal)], [], []),
    'assignUserRequest' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
    'assignUserRole' : IDL.Func([IDL.Principal, IDL.Text], [], []),
    'createAccessRequest' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [IDL.Nat],
        [],
      ),
    'createBed' : IDL.Func([IDL.Nat, Program, IDL.Text], [IDL.Nat], []),
    'createFacility' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'createIntake' : IDL.Func([Client, IDL.Text], [IDL.Nat], []),
    'createReferral' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, Client, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'deleteBed' : IDL.Func([IDL.Nat], [], []),
    'deleteRequest' : IDL.Func([IDL.Nat], [], []),
    'ensureAdminRole' : IDL.Func([], [], []),
    'getActiveBeds' : IDL.Func([], [IDL.Vec(Bed)], ['query']),
    'getActivityLogEntries' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(ActivityLogEntry)],
        ['query'],
      ),
    'getAdminStatusCheck' : IDL.Func([], [AdminStatusInfo], ['query']),
    'getAllBeds' : IDL.Func([], [IDL.Vec(Bed)], ['query']),
    'getAllFacilities' : IDL.Func([], [IDL.Vec(Facility)], ['query']),
    'getAllIntakes' : IDL.Func([], [IDL.Vec(Intake)], ['query']),
    'getAllReferrals' : IDL.Func([], [IDL.Vec(Referral)], ['query']),
    'getAllReferralsForPartnerAgency' : IDL.Func(
        [],
        [IDL.Vec(Referral)],
        ['query'],
      ),
    'getAllUsers' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
        ['query'],
      ),
    'getAvailableBedsByProgram' : IDL.Func(
        [Program],
        [IDL.Vec(Bed)],
        ['query'],
      ),
    'getBedsByProgram' : IDL.Func([Program], [IDL.Vec(Bed)], ['query']),
    'getCallerPartnerAgencyProfile' : IDL.Func(
        [],
        [IDL.Opt(PartnerAgencyProfile)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getIntake' : IDL.Func([IDL.Nat], [Intake], ['query']),
    'getIntakeStatusHistory' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(IntakeStatusHistoryEntry)],
        ['query'],
      ),
    'getMyReferrals' : IDL.Func([], [IDL.Vec(Referral)], ['query']),
    'getPendingRequests' : IDL.Func([], [IDL.Vec(AccessRequest)], ['query']),
    'getReferral' : IDL.Func([IDL.Nat], [Referral], ['query']),
    'getReferralForPartnerAgency' : IDL.Func([IDL.Nat], [Referral], ['query']),
    'getReferralStatusHistory' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(StatusHistoryEntry)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
    'isRequestApproved' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
    'listAdmins' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
    'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
    'markIntakeExited' : IDL.Func([IDL.Nat, Time, IDL.Text], [], []),
    'rejectRequest' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'removeUserRole' : IDL.Func([IDL.Principal], [], []),
    'requestApproval' : IDL.Func([], [], []),
    'requestMoreInfo' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'resubmitReferral' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, Client, IDL.Text],
        [],
        [],
      ),
    'reviewIntake' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'saveCallerPartnerAgencyProfile' : IDL.Func([PartnerAgencyProfile], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
    'updateBed' : IDL.Func(
        [IDL.Nat, Program, IDL.Text, Status__1, IDL.Opt(Client), IDL.Bool],
        [],
        [],
      ),
    'updateBedStatus' : IDL.Func([IDL.Nat, Status__1], [], []),
    'updateReferral' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, Client, IDL.Text],
        [],
        [],
      ),
    'updateReferralStatus' : IDL.Func(
        [IDL.Nat, Status, IDL.Opt(IDL.Principal)],
        [],
        [],
      ),
    'updateReferralStatusWithMessage' : IDL.Func(
        [IDL.Nat, Status, IDL.Opt(IDL.Text)],
        [],
        [],
      ),
    'uploadReferralDocuments' : IDL.Func([IDL.Nat, IDL.Vec(Document)], [], []),
  });
};

export const init = ({ IDL }) => { return []; };