/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AccessRequest {
  'id' : bigint,
  'status' : { 'pending' : null } |
    { 'approved' : null } |
    { 'rejected' : null },
  'contactName' : string,
  'createdAt' : Time,
  'rejectionReason' : [] | [string],
  'email' : string,
  'agencyName' : string,
  'notes' : [] | [string],
  'phone' : string,
  'assignedUser' : [] | [Principal],
}
export type ActionType = { 'referralUpdated' : null } |
  { 'bedArchived' : null } |
  { 'referralStatusChanged' : null } |
  { 'bedAssigned' : null } |
  { 'bedUnassigned' : null } |
  { 'intakeCreated' : null } |
  { 'referralResubmitted' : null } |
  { 'referralCreated' : null } |
  { 'intakeStatusChanged' : null };
export interface ActivityLogEntry {
  'entity' : EntityType,
  'action' : ActionType,
  'user' : Principal,
  'timestamp' : Time,
  'recordId' : bigint,
}
export interface AdminStatusInfo {
  'callerPrincipal' : Principal,
  'isAdmin' : boolean,
  'allAdminPrincipals' : Array<Principal>,
}
export type ApprovalStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface Bed {
  'id' : bigint,
  'status' : Status__1,
  'occupant' : [] | [Client],
  'lastUpdated' : Time,
  'bedNumber' : string,
  'isArchived' : boolean,
  'facilityId' : bigint,
  'program' : Program,
}
export interface Client {
  'contactInfo' : string,
  'name' : string,
  'notes' : [] | [string],
}
export type Document = Uint8Array;
export type EntityType = { 'bed' : null } |
  { 'referral' : null } |
  { 'intake' : null };
export interface Facility {
  'id' : bigint,
  'contactInfo' : string,
  'name' : string,
  'facilityType' : string,
  'address' : string,
}
export interface Intake {
  'id' : bigint,
  'exitDate' : [] | [Time],
  'status' : string,
  'client' : Client,
  'createdAt' : Time,
  'submittedBy' : Principal,
  'statusHistory' : Array<IntakeStatusHistoryEntry>,
  'reviewedBy' : [] | [Principal],
  'updatedAt' : Time,
  'details' : string,
  'exitNotes' : [] | [string],
  'internalNotes' : [] | [string],
  'assignedBedId' : [] | [bigint],
  'caseManager' : [] | [Principal],
}
export interface IntakeStatusHistoryEntry {
  'status' : string,
  'updatedBy' : [] | [Principal],
  'timestamp' : Time,
}
export interface PartnerAgencyProfile {
  'primaryContactName' : string,
  'email' : string,
  'agencyName' : string,
  'phone' : string,
}
export type Program = { 'medicalStepDown' : null } |
  { 'workforceHousing' : null };
export interface Referral {
  'id' : bigint,
  'status' : Status,
  'client' : Client,
  'documents' : Array<Document>,
  'referrerName' : string,
  'clientName' : string,
  'source' : string,
  'partnerAgencyName' : string,
  'createdAt' : Time,
  'submittedBy' : [] | [Principal],
  'statusHistory' : Array<StatusHistoryEntry>,
  'updatedAt' : Time,
  'assignedStaff' : [] | [Principal],
  'programRequested' : string,
  'internalNotes' : [] | [string],
  'requestMoreInfo' : [] | [string],
  'reason' : string,
}
export type Status = { 'submitted' : null } |
  { 'waitlisted' : null } |
  { 'approved' : null } |
  { 'declined' : null } |
  { 'needsInfo' : null };
export interface StatusHistoryEntry {
  'status' : Status,
  'updatedBy' : [] | [Principal],
  'timestamp' : Time,
}
export type Status__1 = { 'occupied' : null } |
  { 'available' : null } |
  { 'maintenance' : null };
export type Time = bigint;
export interface UserApprovalInfo {
  'status' : ApprovalStatus,
  'principal' : Principal,
}
export interface UserProfile {
  'name' : string,
  'role' : [] | [string],
  'email' : [] | [string],
  'phone' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addIntakeInternalNotes' : ActorMethod<[bigint, string], undefined>,
  'addReferralInternalNotes' : ActorMethod<[bigint, string], undefined>,
  'approveReferralAndCreateIntake' : ActorMethod<[bigint, string], Intake>,
  'approveRequest' : ActorMethod<[bigint, Principal], undefined>,
  'archiveBed' : ActorMethod<[bigint], undefined>,
  'assignBed' : ActorMethod<[bigint, Client], undefined>,
  'assignBedToIntake' : ActorMethod<[bigint, bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'assignCaseManager' : ActorMethod<[bigint, [] | [Principal]], undefined>,
  'assignUserRequest' : ActorMethod<[Principal, bigint], undefined>,
  'assignUserRole' : ActorMethod<[Principal, string], undefined>,
  'createAccessRequest' : ActorMethod<
    [string, string, string, string, [] | [string]],
    bigint
  >,
  'createBed' : ActorMethod<[bigint, Program, string], bigint>,
  'createFacility' : ActorMethod<[string, string, string, string], bigint>,
  'createIntake' : ActorMethod<[Client, string], bigint>,
  'createReferral' : ActorMethod<
    [string, string, string, string, Client, string],
    bigint
  >,
  'deleteBed' : ActorMethod<[bigint], undefined>,
  'deleteRequest' : ActorMethod<[bigint], undefined>,
  'ensureAdminRole' : ActorMethod<[], undefined>,
  'getActiveBeds' : ActorMethod<[], Array<Bed>>,
  'getActivityLogEntries' : ActorMethod<
    [bigint, bigint],
    Array<ActivityLogEntry>
  >,
  'getAdminStatusCheck' : ActorMethod<[], AdminStatusInfo>,
  'getAllBeds' : ActorMethod<[], Array<Bed>>,
  'getAllFacilities' : ActorMethod<[], Array<Facility>>,
  'getAllIntakes' : ActorMethod<[], Array<Intake>>,
  'getAllReferrals' : ActorMethod<[], Array<Referral>>,
  'getAllReferralsForPartnerAgency' : ActorMethod<[], Array<Referral>>,
  'getAllUsers' : ActorMethod<[], Array<[Principal, UserProfile]>>,
  'getAvailableBedsByProgram' : ActorMethod<[Program], Array<Bed>>,
  'getBedsByProgram' : ActorMethod<[Program], Array<Bed>>,
  'getCallerPartnerAgencyProfile' : ActorMethod<
    [],
    [] | [PartnerAgencyProfile]
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getIntake' : ActorMethod<[bigint], Intake>,
  'getIntakeStatusHistory' : ActorMethod<
    [bigint],
    Array<IntakeStatusHistoryEntry>
  >,
  'getMyReferrals' : ActorMethod<[], Array<Referral>>,
  'getPendingRequests' : ActorMethod<[], Array<AccessRequest>>,
  'getReferral' : ActorMethod<[bigint], Referral>,
  'getReferralForPartnerAgency' : ActorMethod<[bigint], Referral>,
  'getReferralStatusHistory' : ActorMethod<[bigint], Array<StatusHistoryEntry>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isAdmin' : ActorMethod<[], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isCallerApproved' : ActorMethod<[], boolean>,
  'isRequestApproved' : ActorMethod<[Principal], boolean>,
  'listAdmins' : ActorMethod<[], Array<Principal>>,
  'listApprovals' : ActorMethod<[], Array<UserApprovalInfo>>,
  'markIntakeExited' : ActorMethod<[bigint, Time, string], undefined>,
  'rejectRequest' : ActorMethod<[bigint, string], undefined>,
  'removeUserRole' : ActorMethod<[Principal], undefined>,
  'requestApproval' : ActorMethod<[], undefined>,
  'requestMoreInfo' : ActorMethod<[bigint, string], undefined>,
  'resubmitReferral' : ActorMethod<
    [bigint, string, string, string, string, Client, string],
    undefined
  >,
  'reviewIntake' : ActorMethod<[bigint, string], undefined>,
  'saveCallerPartnerAgencyProfile' : ActorMethod<
    [PartnerAgencyProfile],
    undefined
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setApproval' : ActorMethod<[Principal, ApprovalStatus], undefined>,
  'updateBed' : ActorMethod<
    [bigint, Program, string, Status__1, [] | [Client], boolean],
    undefined
  >,
  'updateBedStatus' : ActorMethod<[bigint, Status__1], undefined>,
  'updateReferral' : ActorMethod<
    [bigint, string, string, string, string, Client, string],
    undefined
  >,
  'updateReferralStatus' : ActorMethod<
    [bigint, Status, [] | [Principal]],
    undefined
  >,
  'updateReferralStatusWithMessage' : ActorMethod<
    [bigint, Status, [] | [string]],
    undefined
  >,
  'uploadReferralDocuments' : ActorMethod<[bigint, Array<Document>], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];