/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Client {
    contactInfo: string;
    name: string;
    notes?: string;
}
export type Time = bigint;
export interface IntakeStatusHistoryEntry {
    status: string;
    updatedBy?: Principal;
    timestamp: Time;
}
export interface AccessRequest {
    id: bigint;
    status: Variant_pending_approved_rejected;
    contactName: string;
    createdAt: Time;
    rejectionReason?: string;
    email: string;
    agencyName: string;
    notes?: string;
    phone: string;
    assignedUser?: Principal;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export type Document = Uint8Array;
export interface Facility {
    id: bigint;
    contactInfo: string;
    name: string;
    facilityType: string;
    address: string;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface Intake {
    id: bigint;
    exitDate?: Time;
    status: string;
    client: Client;
    createdAt: Time;
    submittedBy: Principal;
    statusHistory: Array<IntakeStatusHistoryEntry>;
    reviewedBy?: Principal;
    lastUpdatedBy?: Principal;
    updatedAt: Time;
    details: string;
    exitNotes?: string;
    internalNotes?: string;
    assignedBedId?: bigint;
    caseManager?: Principal;
}
export interface AdminStatusInfo {
    callerPrincipal: Principal;
    isAdmin: boolean;
    allAdminPrincipals: Array<Principal>;
}
export interface ActivityLogEntry {
    entity: EntityType;
    action: ActionType;
    user: Principal;
    timestamp: Time;
    recordId: bigint;
}
export interface StatusHistoryEntry {
    status: Status;
    updatedBy?: Principal;
    timestamp: Time;
}
export interface UserApprovalInfo {
    status: ApprovalStatus;
    principal: Principal;
}
export interface Bed {
    id: bigint;
    status: Status__1;
    occupant?: Client;
    lastUpdated: Time;
    bedNumber: string;
    isArchived: boolean;
    facilityId: bigint;
    program: Program;
}
export interface Referral {
    id: bigint;
    status: Status;
    client: Client;
    documents: Array<Document>;
    referrerName: string;
    clientName: string;
    source: string;
    partnerAgencyName: string;
    createdAt: Time;
    submittedBy?: Principal;
    statusHistory: Array<StatusHistoryEntry>;
    lastUpdatedBy?: Principal;
    updatedAt: Time;
    assignedStaff?: Principal;
    programRequested: string;
    internalNotes?: string;
    requestMoreInfo?: string;
    reason: string;
}
export interface PartnerAgencyProfile {
    primaryContactName: string;
    email: string;
    agencyName: string;
    phone: string;
}
export interface UserProfile {
    name: string;
    role?: string;
    email?: string;
    phone?: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum ActionType {
    referralUpdated = "referralUpdated",
    bedArchived = "bedArchived",
    referralStatusChanged = "referralStatusChanged",
    bedAssigned = "bedAssigned",
    bedUnassigned = "bedUnassigned",
    intakeCreated = "intakeCreated",
    referralResubmitted = "referralResubmitted",
    referralCreated = "referralCreated",
    intakeStatusChanged = "intakeStatusChanged"
}
export enum EntityType {
    bed = "bed",
    referral = "referral",
    intake = "intake"
}
export enum Program {
    medicalStepDown = "medicalStepDown",
    workforceHousing = "workforceHousing"
}
export enum Status {
    submitted = "submitted",
    waitlisted = "waitlisted",
    approved = "approved",
    declined = "declined",
    needsInfo = "needsInfo"
}
export enum Status__1 {
    occupied = "occupied",
    available = "available",
    maintenance = "maintenance"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_pending_approved_rejected {
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addIntakeInternalNotes(intakeId: bigint, notes: string): Promise<void>;
    addReferralInternalNotes(referralId: bigint, notes: string): Promise<void>;
    approveReferralAndCreateIntake(referralId: bigint, intakeDetails: string): Promise<Intake>;
    approveRequest(requestId: bigint, userId: Principal): Promise<void>;
    archiveBed(bedId: bigint): Promise<void>;
    assignBed(bedId: bigint, client: Client): Promise<void>;
    assignBedToIntake(bedId: bigint, intakeId: bigint): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    assignCaseManager(intakeId: bigint, managerId: Principal | null): Promise<void>;
    assignUserRequest(userId: Principal, requestId: bigint): Promise<void>;
    assignUserRole(user: Principal, role: string): Promise<void>;
    createAccessRequest(agencyName: string, contactName: string, phone: string, email: string, notes: string | null): Promise<bigint>;
    createBed(facilityId: bigint, program: Program, bedNumber: string): Promise<bigint>;
    createFacility(name: string, facilityType: string, address: string, contactInfo: string): Promise<bigint>;
    createIntake(client: Client, details: string): Promise<bigint>;
    createReferral(referrerName: string, clientName: string, reason: string, programRequested: string, client: Client, source: string): Promise<bigint>;
    deleteBed(bedId: bigint): Promise<void>;
    deleteRequest(requestId: bigint): Promise<void>;
    getActiveBeds(): Promise<Array<Bed>>;
    getActivityLogEntries(limit: bigint, offset: bigint): Promise<Array<ActivityLogEntry>>;
    getAdminStatusCheck(): Promise<AdminStatusInfo>;
    getAllBeds(): Promise<Array<Bed>>;
    getAllFacilities(): Promise<Array<Facility>>;
    getAllIntakes(): Promise<Array<Intake>>;
    getAllReferrals(): Promise<Array<Referral>>;
    getAllReferralsForPartnerAgency(): Promise<Array<Referral>>;
    getAllUsers(): Promise<Array<[Principal, UserProfile]>>;
    getAvailableBedsByProgram(program: Program): Promise<Array<Bed>>;
    getBedsByProgram(program: Program): Promise<Array<Bed>>;
    getCallerPartnerAgencyProfile(): Promise<PartnerAgencyProfile | null>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getIntake(intakeId: bigint): Promise<Intake>;
    getIntakeStatusHistory(intakeId: bigint): Promise<Array<IntakeStatusHistoryEntry>>;
    getMyReferrals(): Promise<Array<Referral>>;
    getPendingRequests(): Promise<Array<AccessRequest>>;
    getReferral(referralId: bigint): Promise<Referral>;
    getReferralForPartnerAgency(referralId: bigint): Promise<Referral>;
    getReferralStatusHistory(referralId: bigint): Promise<Array<StatusHistoryEntry>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isAdmin(): Promise<boolean>;
    isCallerAdmin(): Promise<boolean>;
    isCallerApproved(): Promise<boolean>;
    isRequestApproved(userId: Principal): Promise<boolean>;
    listAdmins(): Promise<Array<Principal>>;
    listApprovals(): Promise<Array<UserApprovalInfo>>;
    markIntakeExited(intakeId: bigint, exitDate: Time, exitNotes: string): Promise<void>;
    rejectRequest(requestId: bigint, rejectionReason: string): Promise<void>;
    removeUserRole(user: Principal): Promise<void>;
    requestApproval(): Promise<void>;
    requestMoreInfo(referralId: bigint, message: string): Promise<void>;
    resubmitReferral(referralId: bigint, referrerName: string, clientName: string, reason: string, programRequested: string, updatedClient: Client, updatedSource: string): Promise<void>;
    reviewIntake(intakeId: bigint, status: string): Promise<void>;
    saveCallerPartnerAgencyProfile(profile: PartnerAgencyProfile): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    setApproval(user: Principal, status: ApprovalStatus): Promise<void>;
    updateBed(bedId: bigint, newProgram: Program, newNumber: string, newStatus: Status__1, newOccupant: Client | null, newArchived: boolean): Promise<void>;
    updateBedStatus(bedId: bigint, status: Status__1): Promise<void>;
    updateReferral(referralId: bigint, referrerName: string, clientName: string, reason: string, programRequested: string, updatedClient: Client, updatedSource: string): Promise<void>;
    updateReferralStatus(referralId: bigint, status: Status, assignedStaff: Principal | null): Promise<void>;
    updateReferralStatusWithMessage(referralId: bigint, status: Status, message: string | null): Promise<void>;
    uploadReferralDocuments(referralId: bigint, newDocuments: Array<Document>): Promise<void>;
}
import type { AccessRequest as _AccessRequest, ActionType as _ActionType, ActivityLogEntry as _ActivityLogEntry, ApprovalStatus as _ApprovalStatus, Bed as _Bed, Client as _Client, Document as _Document, EntityType as _EntityType, Intake as _Intake, IntakeStatusHistoryEntry as _IntakeStatusHistoryEntry, PartnerAgencyProfile as _PartnerAgencyProfile, Program as _Program, Referral as _Referral, Status as _Status, StatusHistoryEntry as _StatusHistoryEntry, Status__1 as _Status__1, Time as _Time, UserApprovalInfo as _UserApprovalInfo, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addIntakeInternalNotes(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addIntakeInternalNotes(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addIntakeInternalNotes(arg0, arg1);
            return result;
        }
    }
    async addReferralInternalNotes(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addReferralInternalNotes(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addReferralInternalNotes(arg0, arg1);
            return result;
        }
    }
    async approveReferralAndCreateIntake(arg0: bigint, arg1: string): Promise<Intake> {
        if (this.processError) {
            try {
                const result = await this.actor.approveReferralAndCreateIntake(arg0, arg1);
                return from_candid_Intake_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveReferralAndCreateIntake(arg0, arg1);
            return from_candid_Intake_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async approveRequest(arg0: bigint, arg1: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.approveRequest(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveRequest(arg0, arg1);
            return result;
        }
    }
    async archiveBed(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.archiveBed(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.archiveBed(arg0);
            return result;
        }
    }
    async assignBed(arg0: bigint, arg1: Client): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignBed(arg0, to_candid_Client_n18(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignBed(arg0, to_candid_Client_n18(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async assignBedToIntake(arg0: bigint, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignBedToIntake(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignBedToIntake(arg0, arg1);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n20(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n20(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async assignCaseManager(arg0: bigint, arg1: Principal | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCaseManager(arg0, to_candid_opt_n22(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCaseManager(arg0, to_candid_opt_n22(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async assignUserRequest(arg0: Principal, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignUserRequest(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignUserRequest(arg0, arg1);
            return result;
        }
    }
    async assignUserRole(arg0: Principal, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignUserRole(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignUserRole(arg0, arg1);
            return result;
        }
    }
    async createAccessRequest(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string | null): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createAccessRequest(arg0, arg1, arg2, arg3, to_candid_opt_n23(this._uploadFile, this._downloadFile, arg4));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createAccessRequest(arg0, arg1, arg2, arg3, to_candid_opt_n23(this._uploadFile, this._downloadFile, arg4));
            return result;
        }
    }
    async createBed(arg0: bigint, arg1: Program, arg2: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createBed(arg0, to_candid_Program_n24(this._uploadFile, this._downloadFile, arg1), arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createBed(arg0, to_candid_Program_n24(this._uploadFile, this._downloadFile, arg1), arg2);
            return result;
        }
    }
    async createFacility(arg0: string, arg1: string, arg2: string, arg3: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createFacility(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createFacility(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async createIntake(arg0: Client, arg1: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createIntake(to_candid_Client_n18(this._uploadFile, this._downloadFile, arg0), arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createIntake(to_candid_Client_n18(this._uploadFile, this._downloadFile, arg0), arg1);
            return result;
        }
    }
    async createReferral(arg0: string, arg1: string, arg2: string, arg3: string, arg4: Client, arg5: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createReferral(arg0, arg1, arg2, arg3, to_candid_Client_n18(this._uploadFile, this._downloadFile, arg4), arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createReferral(arg0, arg1, arg2, arg3, to_candid_Client_n18(this._uploadFile, this._downloadFile, arg4), arg5);
            return result;
        }
    }
    async deleteBed(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteBed(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteBed(arg0);
            return result;
        }
    }
    async deleteRequest(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteRequest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteRequest(arg0);
            return result;
        }
    }
    async getActiveBeds(): Promise<Array<Bed>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActiveBeds();
                return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActiveBeds();
            return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getActivityLogEntries(arg0: bigint, arg1: bigint): Promise<Array<ActivityLogEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActivityLogEntries(arg0, arg1);
                return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActivityLogEntries(arg0, arg1);
            return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAdminStatusCheck(): Promise<AdminStatusInfo> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminStatusCheck();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminStatusCheck();
            return result;
        }
    }
    async getAllBeds(): Promise<Array<Bed>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllBeds();
                return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllBeds();
            return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllFacilities(): Promise<Array<Facility>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllFacilities();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllFacilities();
            return result;
        }
    }
    async getAllIntakes(): Promise<Array<Intake>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllIntakes();
                return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllIntakes();
            return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllReferrals(): Promise<Array<Referral>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllReferrals();
                return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllReferrals();
            return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllReferralsForPartnerAgency(): Promise<Array<Referral>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllReferralsForPartnerAgency();
                return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllReferralsForPartnerAgency();
            return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllUsers(): Promise<Array<[Principal, UserProfile]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUsers();
                return from_candid_vec_n50(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUsers();
            return from_candid_vec_n50(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAvailableBedsByProgram(arg0: Program): Promise<Array<Bed>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAvailableBedsByProgram(to_candid_Program_n24(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAvailableBedsByProgram(to_candid_Program_n24(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBedsByProgram(arg0: Program): Promise<Array<Bed>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBedsByProgram(to_candid_Program_n24(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBedsByProgram(to_candid_Program_n24(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerPartnerAgencyProfile(): Promise<PartnerAgencyProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerPartnerAgencyProfile();
                return from_candid_opt_n54(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerPartnerAgencyProfile();
            return from_candid_opt_n54(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n55(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n55(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n56(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n56(this._uploadFile, this._downloadFile, result);
        }
    }
    async getIntake(arg0: bigint): Promise<Intake> {
        if (this.processError) {
            try {
                const result = await this.actor.getIntake(arg0);
                return from_candid_Intake_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getIntake(arg0);
            return from_candid_Intake_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getIntakeStatusHistory(arg0: bigint): Promise<Array<IntakeStatusHistoryEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getIntakeStatusHistory(arg0);
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getIntakeStatusHistory(arg0);
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyReferrals(): Promise<Array<Referral>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyReferrals();
                return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyReferrals();
            return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPendingRequests(): Promise<Array<AccessRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPendingRequests();
                return from_candid_vec_n58(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPendingRequests();
            return from_candid_vec_n58(this._uploadFile, this._downloadFile, result);
        }
    }
    async getReferral(arg0: bigint): Promise<Referral> {
        if (this.processError) {
            try {
                const result = await this.actor.getReferral(arg0);
                return from_candid_Referral_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReferral(arg0);
            return from_candid_Referral_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async getReferralForPartnerAgency(arg0: bigint): Promise<Referral> {
        if (this.processError) {
            try {
                const result = await this.actor.getReferralForPartnerAgency(arg0);
                return from_candid_Referral_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReferralForPartnerAgency(arg0);
            return from_candid_Referral_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async getReferralStatusHistory(arg0: bigint): Promise<Array<StatusHistoryEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getReferralStatusHistory(arg0);
                return from_candid_vec_n47(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReferralStatusHistory(arg0);
            return from_candid_vec_n47(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n55(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n55(this._uploadFile, this._downloadFile, result);
        }
    }
    async isAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isAdmin();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isCallerApproved(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerApproved();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerApproved();
            return result;
        }
    }
    async isRequestApproved(arg0: Principal): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isRequestApproved(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isRequestApproved(arg0);
            return result;
        }
    }
    async listAdmins(): Promise<Array<Principal>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAdmins();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAdmins();
            return result;
        }
    }
    async listApprovals(): Promise<Array<UserApprovalInfo>> {
        if (this.processError) {
            try {
                const result = await this.actor.listApprovals();
                return from_candid_vec_n62(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listApprovals();
            return from_candid_vec_n62(this._uploadFile, this._downloadFile, result);
        }
    }
    async markIntakeExited(arg0: bigint, arg1: Time, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markIntakeExited(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markIntakeExited(arg0, arg1, arg2);
            return result;
        }
    }
    async rejectRequest(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectRequest(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectRequest(arg0, arg1);
            return result;
        }
    }
    async removeUserRole(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeUserRole(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeUserRole(arg0);
            return result;
        }
    }
    async requestApproval(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.requestApproval();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.requestApproval();
            return result;
        }
    }
    async requestMoreInfo(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.requestMoreInfo(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.requestMoreInfo(arg0, arg1);
            return result;
        }
    }
    async resubmitReferral(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: string, arg5: Client, arg6: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.resubmitReferral(arg0, arg1, arg2, arg3, arg4, to_candid_Client_n18(this._uploadFile, this._downloadFile, arg5), arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resubmitReferral(arg0, arg1, arg2, arg3, arg4, to_candid_Client_n18(this._uploadFile, this._downloadFile, arg5), arg6);
            return result;
        }
    }
    async reviewIntake(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.reviewIntake(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.reviewIntake(arg0, arg1);
            return result;
        }
    }
    async saveCallerPartnerAgencyProfile(arg0: PartnerAgencyProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerPartnerAgencyProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerPartnerAgencyProfile(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n66(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n66(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async setApproval(arg0: Principal, arg1: ApprovalStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setApproval(arg0, to_candid_ApprovalStatus_n68(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setApproval(arg0, to_candid_ApprovalStatus_n68(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateBed(arg0: bigint, arg1: Program, arg2: string, arg3: Status__1, arg4: Client | null, arg5: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBed(arg0, to_candid_Program_n24(this._uploadFile, this._downloadFile, arg1), arg2, to_candid_Status__1_n70(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n72(this._uploadFile, this._downloadFile, arg4), arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBed(arg0, to_candid_Program_n24(this._uploadFile, this._downloadFile, arg1), arg2, to_candid_Status__1_n70(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n72(this._uploadFile, this._downloadFile, arg4), arg5);
            return result;
        }
    }
    async updateBedStatus(arg0: bigint, arg1: Status__1): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBedStatus(arg0, to_candid_Status__1_n70(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBedStatus(arg0, to_candid_Status__1_n70(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateReferral(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: string, arg5: Client, arg6: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateReferral(arg0, arg1, arg2, arg3, arg4, to_candid_Client_n18(this._uploadFile, this._downloadFile, arg5), arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateReferral(arg0, arg1, arg2, arg3, arg4, to_candid_Client_n18(this._uploadFile, this._downloadFile, arg5), arg6);
            return result;
        }
    }
    async updateReferralStatus(arg0: bigint, arg1: Status, arg2: Principal | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateReferralStatus(arg0, to_candid_Status_n73(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n22(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateReferralStatus(arg0, to_candid_Status_n73(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n22(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async updateReferralStatusWithMessage(arg0: bigint, arg1: Status, arg2: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateReferralStatusWithMessage(arg0, to_candid_Status_n73(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n23(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateReferralStatusWithMessage(arg0, to_candid_Status_n73(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n23(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async uploadReferralDocuments(arg0: bigint, arg1: Array<Document>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadReferralDocuments(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadReferralDocuments(arg0, arg1);
            return result;
        }
    }
}
function from_candid_AccessRequest_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AccessRequest): AccessRequest {
    return from_candid_record_n60(_uploadFile, _downloadFile, value);
}
function from_candid_ActionType_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ActionType): ActionType {
    return from_candid_variant_n40(_uploadFile, _downloadFile, value);
}
function from_candid_ActivityLogEntry_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ActivityLogEntry): ActivityLogEntry {
    return from_candid_record_n36(_uploadFile, _downloadFile, value);
}
function from_candid_ApprovalStatus_n65(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ApprovalStatus): ApprovalStatus {
    return from_candid_variant_n61(_uploadFile, _downloadFile, value);
}
function from_candid_Bed_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Bed): Bed {
    return from_candid_record_n28(_uploadFile, _downloadFile, value);
}
function from_candid_Client_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Client): Client {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_EntityType_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EntityType): EntityType {
    return from_candid_variant_n38(_uploadFile, _downloadFile, value);
}
function from_candid_IntakeStatusHistoryEntry_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _IntakeStatusHistoryEntry): IntakeStatusHistoryEntry {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_Intake_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Intake): Intake {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_Program_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Program): Program {
    return from_candid_variant_n33(_uploadFile, _downloadFile, value);
}
function from_candid_Referral_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Referral): Referral {
    return from_candid_record_n44(_uploadFile, _downloadFile, value);
}
function from_candid_StatusHistoryEntry_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StatusHistoryEntry): StatusHistoryEntry {
    return from_candid_record_n49(_uploadFile, _downloadFile, value);
}
function from_candid_Status__1_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Status__1): Status__1 {
    return from_candid_variant_n30(_uploadFile, _downloadFile, value);
}
function from_candid_Status_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Status): Status {
    return from_candid_variant_n46(_uploadFile, _downloadFile, value);
}
function from_candid_UserApprovalInfo_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserApprovalInfo): UserApprovalInfo {
    return from_candid_record_n64(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n53(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n57(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Time]): Time | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Client]): Client | null {
    return value.length === 0 ? null : from_candid_Client_n11(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PartnerAgencyProfile]): PartnerAgencyProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n52(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    contactInfo: string;
    name: string;
    notes: [] | [string];
}): {
    contactInfo: string;
    name: string;
    notes?: string;
} {
    return {
        contactInfo: value.contactInfo,
        name: value.name,
        notes: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.notes))
    };
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: string;
    updatedBy: [] | [Principal];
    timestamp: _Time;
}): {
    status: string;
    updatedBy?: Principal;
    timestamp: Time;
} {
    return {
        status: value.status,
        updatedBy: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.updatedBy)),
        timestamp: value.timestamp
    };
}
function from_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _Status__1;
    occupant: [] | [_Client];
    lastUpdated: _Time;
    bedNumber: string;
    isArchived: boolean;
    facilityId: bigint;
    program: _Program;
}): {
    id: bigint;
    status: Status__1;
    occupant?: Client;
    lastUpdated: Time;
    bedNumber: string;
    isArchived: boolean;
    facilityId: bigint;
    program: Program;
} {
    return {
        id: value.id,
        status: from_candid_Status__1_n29(_uploadFile, _downloadFile, value.status),
        occupant: record_opt_to_undefined(from_candid_opt_n31(_uploadFile, _downloadFile, value.occupant)),
        lastUpdated: value.lastUpdated,
        bedNumber: value.bedNumber,
        isArchived: value.isArchived,
        facilityId: value.facilityId,
        program: from_candid_Program_n32(_uploadFile, _downloadFile, value.program)
    };
}
function from_candid_record_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    entity: _EntityType;
    action: _ActionType;
    user: Principal;
    timestamp: _Time;
    recordId: bigint;
}): {
    entity: EntityType;
    action: ActionType;
    user: Principal;
    timestamp: Time;
    recordId: bigint;
} {
    return {
        entity: from_candid_EntityType_n37(_uploadFile, _downloadFile, value.entity),
        action: from_candid_ActionType_n39(_uploadFile, _downloadFile, value.action),
        user: value.user,
        timestamp: value.timestamp,
        recordId: value.recordId
    };
}
function from_candid_record_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _Status;
    client: _Client;
    documents: Array<_Document>;
    referrerName: string;
    clientName: string;
    source: string;
    partnerAgencyName: string;
    createdAt: _Time;
    submittedBy: [] | [Principal];
    statusHistory: Array<_StatusHistoryEntry>;
    lastUpdatedBy: [] | [Principal];
    updatedAt: _Time;
    assignedStaff: [] | [Principal];
    programRequested: string;
    internalNotes: [] | [string];
    requestMoreInfo: [] | [string];
    reason: string;
}): {
    id: bigint;
    status: Status;
    client: Client;
    documents: Array<Document>;
    referrerName: string;
    clientName: string;
    source: string;
    partnerAgencyName: string;
    createdAt: Time;
    submittedBy?: Principal;
    statusHistory: Array<StatusHistoryEntry>;
    lastUpdatedBy?: Principal;
    updatedAt: Time;
    assignedStaff?: Principal;
    programRequested: string;
    internalNotes?: string;
    requestMoreInfo?: string;
    reason: string;
} {
    return {
        id: value.id,
        status: from_candid_Status_n45(_uploadFile, _downloadFile, value.status),
        client: from_candid_Client_n11(_uploadFile, _downloadFile, value.client),
        documents: value.documents,
        referrerName: value.referrerName,
        clientName: value.clientName,
        source: value.source,
        partnerAgencyName: value.partnerAgencyName,
        createdAt: value.createdAt,
        submittedBy: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.submittedBy)),
        statusHistory: from_candid_vec_n47(_uploadFile, _downloadFile, value.statusHistory),
        lastUpdatedBy: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.lastUpdatedBy)),
        updatedAt: value.updatedAt,
        assignedStaff: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.assignedStaff)),
        programRequested: value.programRequested,
        internalNotes: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.internalNotes)),
        requestMoreInfo: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.requestMoreInfo)),
        reason: value.reason
    };
}
function from_candid_record_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _Status;
    updatedBy: [] | [Principal];
    timestamp: _Time;
}): {
    status: Status;
    updatedBy?: Principal;
    timestamp: Time;
} {
    return {
        status: from_candid_Status_n45(_uploadFile, _downloadFile, value.status),
        updatedBy: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.updatedBy)),
        timestamp: value.timestamp
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_record_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    role: [] | [string];
    email: [] | [string];
    phone: [] | [string];
}): {
    name: string;
    role?: string;
    email?: string;
    phone?: string;
} {
    return {
        name: value.name,
        role: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.role)),
        email: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.email)),
        phone: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.phone))
    };
}
function from_candid_record_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: {
        pending: null;
    } | {
        approved: null;
    } | {
        rejected: null;
    };
    contactName: string;
    createdAt: _Time;
    rejectionReason: [] | [string];
    email: string;
    agencyName: string;
    notes: [] | [string];
    phone: string;
    assignedUser: [] | [Principal];
}): {
    id: bigint;
    status: Variant_pending_approved_rejected;
    contactName: string;
    createdAt: Time;
    rejectionReason?: string;
    email: string;
    agencyName: string;
    notes?: string;
    phone: string;
    assignedUser?: Principal;
} {
    return {
        id: value.id,
        status: from_candid_variant_n61(_uploadFile, _downloadFile, value.status),
        contactName: value.contactName,
        createdAt: value.createdAt,
        rejectionReason: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.rejectionReason)),
        email: value.email,
        agencyName: value.agencyName,
        notes: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.notes)),
        phone: value.phone,
        assignedUser: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.assignedUser))
    };
}
function from_candid_record_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _ApprovalStatus;
    principal: Principal;
}): {
    status: ApprovalStatus;
    principal: Principal;
} {
    return {
        status: from_candid_ApprovalStatus_n65(_uploadFile, _downloadFile, value.status),
        principal: value.principal
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    exitDate: [] | [_Time];
    status: string;
    client: _Client;
    createdAt: _Time;
    submittedBy: Principal;
    statusHistory: Array<_IntakeStatusHistoryEntry>;
    reviewedBy: [] | [Principal];
    lastUpdatedBy: [] | [Principal];
    updatedAt: _Time;
    details: string;
    exitNotes: [] | [string];
    internalNotes: [] | [string];
    assignedBedId: [] | [bigint];
    caseManager: [] | [Principal];
}): {
    id: bigint;
    exitDate?: Time;
    status: string;
    client: Client;
    createdAt: Time;
    submittedBy: Principal;
    statusHistory: Array<IntakeStatusHistoryEntry>;
    reviewedBy?: Principal;
    lastUpdatedBy?: Principal;
    updatedAt: Time;
    details: string;
    exitNotes?: string;
    internalNotes?: string;
    assignedBedId?: bigint;
    caseManager?: Principal;
} {
    return {
        id: value.id,
        exitDate: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.exitDate)),
        status: value.status,
        client: from_candid_Client_n11(_uploadFile, _downloadFile, value.client),
        createdAt: value.createdAt,
        submittedBy: value.submittedBy,
        statusHistory: from_candid_vec_n14(_uploadFile, _downloadFile, value.statusHistory),
        reviewedBy: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.reviewedBy)),
        lastUpdatedBy: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.lastUpdatedBy)),
        updatedAt: value.updatedAt,
        details: value.details,
        exitNotes: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.exitNotes)),
        internalNotes: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.internalNotes)),
        assignedBedId: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.assignedBedId)),
        caseManager: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.caseManager))
    };
}
function from_candid_tuple_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [Principal, _UserProfile]): [Principal, UserProfile] {
    return [
        value[0],
        from_candid_UserProfile_n52(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    occupied: null;
} | {
    available: null;
} | {
    maintenance: null;
}): Status__1 {
    return "occupied" in value ? Status__1.occupied : "available" in value ? Status__1.available : "maintenance" in value ? Status__1.maintenance : value;
}
function from_candid_variant_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    medicalStepDown: null;
} | {
    workforceHousing: null;
}): Program {
    return "medicalStepDown" in value ? Program.medicalStepDown : "workforceHousing" in value ? Program.workforceHousing : value;
}
function from_candid_variant_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bed: null;
} | {
    referral: null;
} | {
    intake: null;
}): EntityType {
    return "bed" in value ? EntityType.bed : "referral" in value ? EntityType.referral : "intake" in value ? EntityType.intake : value;
}
function from_candid_variant_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    referralUpdated: null;
} | {
    bedArchived: null;
} | {
    referralStatusChanged: null;
} | {
    bedAssigned: null;
} | {
    bedUnassigned: null;
} | {
    intakeCreated: null;
} | {
    referralResubmitted: null;
} | {
    referralCreated: null;
} | {
    intakeStatusChanged: null;
}): ActionType {
    return "referralUpdated" in value ? ActionType.referralUpdated : "bedArchived" in value ? ActionType.bedArchived : "referralStatusChanged" in value ? ActionType.referralStatusChanged : "bedAssigned" in value ? ActionType.bedAssigned : "bedUnassigned" in value ? ActionType.bedUnassigned : "intakeCreated" in value ? ActionType.intakeCreated : "referralResubmitted" in value ? ActionType.referralResubmitted : "referralCreated" in value ? ActionType.referralCreated : "intakeStatusChanged" in value ? ActionType.intakeStatusChanged : value;
}
function from_candid_variant_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    submitted: null;
} | {
    waitlisted: null;
} | {
    approved: null;
} | {
    declined: null;
} | {
    needsInfo: null;
}): Status {
    return "submitted" in value ? Status.submitted : "waitlisted" in value ? Status.waitlisted : "approved" in value ? Status.approved : "declined" in value ? Status.declined : "needsInfo" in value ? Status.needsInfo : value;
}
function from_candid_variant_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
}): Variant_pending_approved_rejected {
    return "pending" in value ? Variant_pending_approved_rejected.pending : "approved" in value ? Variant_pending_approved_rejected.approved : "rejected" in value ? Variant_pending_approved_rejected.rejected : value;
}
function from_candid_vec_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_IntakeStatusHistoryEntry>): Array<IntakeStatusHistoryEntry> {
    return value.map((x)=>from_candid_IntakeStatusHistoryEntry_n15(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Bed>): Array<Bed> {
    return value.map((x)=>from_candid_Bed_n27(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ActivityLogEntry>): Array<ActivityLogEntry> {
    return value.map((x)=>from_candid_ActivityLogEntry_n35(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Intake>): Array<Intake> {
    return value.map((x)=>from_candid_Intake_n8(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Referral>): Array<Referral> {
    return value.map((x)=>from_candid_Referral_n43(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_StatusHistoryEntry>): Array<StatusHistoryEntry> {
    return value.map((x)=>from_candid_StatusHistoryEntry_n48(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[Principal, _UserProfile]>): Array<[Principal, UserProfile]> {
    return value.map((x)=>from_candid_tuple_n51(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AccessRequest>): Array<AccessRequest> {
    return value.map((x)=>from_candid_AccessRequest_n59(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserApprovalInfo>): Array<UserApprovalInfo> {
    return value.map((x)=>from_candid_UserApprovalInfo_n63(_uploadFile, _downloadFile, x));
}
function to_candid_ApprovalStatus_n68(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ApprovalStatus): _ApprovalStatus {
    return to_candid_variant_n69(_uploadFile, _downloadFile, value);
}
function to_candid_Client_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Client): _Client {
    return to_candid_record_n19(_uploadFile, _downloadFile, value);
}
function to_candid_Program_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Program): _Program {
    return to_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function to_candid_Status__1_n70(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Status__1): _Status__1 {
    return to_candid_variant_n71(_uploadFile, _downloadFile, value);
}
function to_candid_Status_n73(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Status): _Status {
    return to_candid_variant_n74(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n66(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n67(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Principal | null): [] | [Principal] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n72(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Client | null): [] | [_Client] {
    return value === null ? candid_none() : candid_some(to_candid_Client_n18(_uploadFile, _downloadFile, value));
}
function to_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    contactInfo: string;
    name: string;
    notes?: string;
}): {
    contactInfo: string;
    name: string;
    notes: [] | [string];
} {
    return {
        contactInfo: value.contactInfo,
        name: value.name,
        notes: value.notes ? candid_some(value.notes) : candid_none()
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n67(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    role?: string;
    email?: string;
    phone?: string;
}): {
    name: string;
    role: [] | [string];
    email: [] | [string];
    phone: [] | [string];
} {
    return {
        name: value.name,
        role: value.role ? candid_some(value.role) : candid_none(),
        email: value.email ? candid_some(value.email) : candid_none(),
        phone: value.phone ? candid_some(value.phone) : candid_none()
    };
}
function to_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Program): {
    medicalStepDown: null;
} | {
    workforceHousing: null;
} {
    return value == Program.medicalStepDown ? {
        medicalStepDown: null
    } : value == Program.workforceHousing ? {
        workforceHousing: null
    } : value;
}
function to_candid_variant_n69(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_pending_approved_rejected): {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
} {
    return value == Variant_pending_approved_rejected.pending ? {
        pending: null
    } : value == Variant_pending_approved_rejected.approved ? {
        approved: null
    } : value == Variant_pending_approved_rejected.rejected ? {
        rejected: null
    } : value;
}
function to_candid_variant_n71(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Status__1): {
    occupied: null;
} | {
    available: null;
} | {
    maintenance: null;
} {
    return value == Status__1.occupied ? {
        occupied: null
    } : value == Status__1.available ? {
        available: null
    } : value == Status__1.maintenance ? {
        maintenance: null
    } : value;
}
function to_candid_variant_n74(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Status): {
    submitted: null;
} | {
    waitlisted: null;
} | {
    approved: null;
} | {
    declined: null;
} | {
    needsInfo: null;
} {
    return value == Status.submitted ? {
        submitted: null
    } : value == Status.waitlisted ? {
        waitlisted: null
    } : value == Status.approved ? {
        approved: null
    } : value == Status.declined ? {
        declined: null
    } : value == Status.needsInfo ? {
        needsInfo: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
